Make positioning of barriers random. Use parameters defined in config.
adessoSE/BrainySnake pull request #53
Opened 2018-02-13 12:23 UTC by dariobraun

Fixes #30

2018-02-14 18:37 UTC, FlorianTim requested changes

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +                if (counter > 50) {
Keine magic number

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +                    break outer_loop;
Mir wäre eine Methode lieber

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +    private Point2D generateBarrierPosition() {
Ich denke das können wir besser machen.
z.B. Könnten wir eine Liste der verbleibenden Punkte (Felder) haben und dann random auf diese Liste zugreifen.
Diese Liste könnten wir dann danach z.B. zum platzieren der Äpfel nutzen

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +    private Point2D generateBarrierPosition() {
Ok, eine Liste mit belegten Punkten hast du schon,
 dann schaue doch mal ob du eine Liste mit freien Punkten pflegst

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +        for (Point2D point : points) {
Die Komplexität ist hier schon recht hoch, weil das die dritte Schleife ist

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +    private boolean isConflicting(List<Point2D> points, Point2D newPoint) {
JavaDoc bitte mit /** */

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +        LinkedList<Point2D> barriers = new LinkedList<>();
Bitte
- package private machen
- JavaDoc hinzufügen
- UnitTest hinzufügen

2018-02-14 18:37 UTC, FlorianTim commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +        List<Point2D> barrierDots = new ArrayList<>();
Barrier könnte auch eine eigene Klasse sein

2018-02-15 07:55 UTC, dariobraun commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +        LinkedList<Point2D> barriers = new LinkedList<>();
Worauf genau bezieht sich das "package private machen"?

2018-02-15 10:58 UTC, dariobraun commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +        LinkedList<Point2D> barriers = new LinkedList<>();
Worauf bezieht sich das "package-private machen"?

2018-02-15 11:48 UTC, dariobraun commented on core/src/de/adesso/brainysnake/Gamelogic/Level/Level.java
> +        for (Point2D point : points) {
Ich hab's leider nicht geschafft die Komplexität überall unter 3 zu halten

2018-02-19 16:48 UTC, FlorianTim approved these changes

2018-02-19 17:00 UTC, merged