Player agent
adessoSE/BrainySnake pull request #65
Opened 2018-02-18 13:16 UTC by AlexanderBrockmann

Added a new KI agent to see if bugs occur.

2018-02-20 14:31 UTC, RudiKlassen-zz requested changes

2018-02-20 14:31 UTC, RudiKlassen-zz commented on playercommon/src/de/adesso/brainysnake/playercommon/Orientation.java
> +    AHEAD,
Not necessary. _Ahead_ ist the default, when no other actions called.

2018-02-20 14:31 UTC, RudiKlassen-zz commented on .gitignore
> +build/
Pls move this change to a new PR. Could you pls explain this change?

2018-02-26 09:15 UTC, AlexanderBrockmann commented on playercommon/src/de/adesso/brainysnake/playercommon/Orientation.java
> +    AHEAD,
Can be ignored, the Enum is useless in the current version.

2018-02-26 10:24 UTC, closed without merging